### ISSUE TITLE
Colors on the lines of a performance profile

### ISSUE THREAD

**Issue by SamaraVilar** [JuliaSmoothOptimizers/JuliaSmoothOptimizers.github.io#172]
Hello. I have a question about the "BenchmarkProfiles" package. I would like to know if it is possible to change the colors of the lines of a performance profile, because when I try to modify it in my code, an error appears.

**Comment by tmigot** [comment]
Hi @SamaraVilar !
Thanks for the question, it would be easier for us to help you if you provide a MWE (minimal working example) of what you tried as well as the errors.
The keyword arguments you pass to `performance_profile` are then passed to `plot` so changing colors might depend on the backend used. For instance, with Plots.jl, it should be `lc`.
